name: Run Restassured Tests

on:
  push:
    branches:
      - main  # Change this to your default branch if different
    paths:
      - 'src/main/java/App.java'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Selenium tests
        run: |
          mvn test -DsuiteXmlFile=testng.xml
        shell: bash